/**
 * Curated icon registry.
 *
 * Data records reference icons by *name* (so they can be edited from the admin
 * panel), but `import * as Icons from 'lucide-react'` defeats tree-shaking and
 * pulls the entire ~1.4 MB icon library into the shared vendor chunk.
 *
 * This registry imports only the icons the product actually uses, keeping the
 * name-based indirection while shipping ~60 icons instead of ~1,500.
 * Adding a new icon to a data record = adding one line here.
 */
import {
  Activity,
  Armchair,
  ArrowUpDown,
  BadgeCheck,
  BarChart3,
  Box,
  Briefcase,
  Bug,
  Building2,
  Cable,
  Calculator,
  CalendarCheck,
  CalendarClock,
  ChefHat,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  Cpu,
  DoorClosed,
  Download,
  Droplets,
  Eye,
  Fan,
  Fence,
  FileBarChart,
  FileText,
  FileUser,
  FlameKindling,
  FolderOpen,
  GanttChartSquare,
  Hammer,
  HardHat,
  Headset,
  HelpCircle,
  Home,
  Images,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutPanelTop,
  LayoutTemplate,
  Lightbulb,
  Menu,
  Newspaper,
  Palette,
  PanelBottom,
  PencilRuler,
  Presentation,
  Quote,
  ReceiptIndianRupee,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sofa,
  Sparkles,
  Square,
  Stamp,
  Store,
  Sun,
  Target,
  Trees,
  Truck,
  Umbrella,
  UserCog,
  Users,
  Video,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  Activity,
  Armchair,
  ArrowUpDown,
  BadgeCheck,
  BarChart3,
  Box,
  Briefcase,
  Bug,
  Building2,
  Cable,
  Calculator,
  CalendarCheck,
  CalendarClock,
  ChefHat,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  Cpu,
  DoorClosed,
  Download,
  Droplets,
  Eye,
  Fan,
  Fence,
  FileBarChart,
  FileText,
  FileUser,
  FlameKindling,
  FolderOpen,
  GanttChartSquare,
  Hammer,
  HardHat,
  Headset,
  HelpCircle,
  Home,
  Images,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutPanelTop,
  LayoutTemplate,
  Lightbulb,
  Menu,
  Newspaper,
  Palette,
  PanelBottom,
  PencilRuler,
  Presentation,
  Quote,
  ReceiptIndianRupee,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sofa,
  Sparkles,
  Square,
  Stamp,
  Store,
  Sun,
  Target,
  Trees,
  Truck,
  Umbrella,
  UserCog,
  Users,
  Video,
  Workflow,
  Wrench,
  Zap,
};

/** Render an icon by its registry name. Falls back to a neutral square. */
export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = ICONS[name] ?? Square;
  return <Cmp className={className} aria-hidden />;
}

export const ICON_NAMES = Object.keys(ICONS);
